version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: db_reserva_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_reserva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
